using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;

namespace CarTrackingSystem
{
    public partial class Browse_Cars : System.Web.UI.Page
    {
      protected void Page_Load(object sender, EventArgs e)
      {
        var dataSource = (IQueryable) Session["DataSource"];
        string department = (string)Session["Department"];

        if (Session["Employee_ID"] == null || department == null)
          Response.Redirect("Login.aspx");

        if (department == "Admin")
          GridView1.AutoGenerateDeleteButton = true;
        else
          GridView1.AutoGenerateDeleteButton = false;

        if (!Page.IsPostBack)
        {
          int carID = 0;
          if(Session["Car_ID"] != null && Session["PreviousPage"] !=null){
            carID = (int)Session["Car_ID"];
            tbCarID.Text = carID.ToString();
          }

          VWCTSDataContext db = new VWCTSDataContext();
          //using(VWCTSDataContext db = new VWCTSDataContext()){
            var source = from n in db.Cars
                         where n.Status == "On Lot"
                         select n;

            var gridSource = from n in source
                          select new
                          {
                            ID = n.Car_ID, Model = n.Model, Trim = n.Trim,
                            Color = n.Color, Transmission = n.Transmission,
                            Location = n.Location, Price = n.Price
                          };

            GridView1.DataSource = gridSource;
            Session["DataSource"] = source;
            GridView1.DataBind();
          //}
        }

        lblCarID.ForeColor = System.Drawing.ColorTranslator.FromHtml("#606760");
        lblModel.ForeColor = System.Drawing.ColorTranslator.FromHtml("#606760");
        lblTrim.ForeColor = System.Drawing.ColorTranslator.FromHtml("#606760");
        lblColor.ForeColor = System.Drawing.ColorTranslator.FromHtml("#606760");
        lblTransmission.ForeColor = System.Drawing.ColorTranslator.FromHtml("#606760");
        lblListPrice.ForeColor = System.Drawing.ColorTranslator.FromHtml("#606760");

      }


      protected void ddlModel_SelectedIndexChanged(object sender, EventArgs e)
      {
          ddlTrim.Items.Clear();
          ListItem newItem = new ListItem();
          newItem.Value = "";
          ddlTrim.Items.Add(newItem);
          ddlTrim.DataBind();
      }

      protected void ddlTrim_SelectedIndexChanged(object sender, EventArgs e)
      {

      }

      protected void Button1_Click(object sender, EventArgs e)
      {
        VWCTSDataContext db = new VWCTSDataContext();
        var queryResults = from n in db.Cars
                           where n.Status == "On Lot"
                           select n;

        if (tbCarID.Text != "")
        {
          int id = 0;
          if(!int.TryParse(tbCarID.Text, out id)){
            lblCarID.ForeColor = System.Drawing.Color.Red;
            return;
          }

          queryResults = from n in queryResults
                         where id == n.Car_ID
                         select n;
        }

        if (ddlModel.SelectedValue != "")
        {
          queryResults = from n in queryResults
                         where ddlModel.SelectedValue == n.Model
                         select n;
        }


        if (ddlTrim.Text != "")
        {
          queryResults = from n in queryResults
                         where ddlTrim.SelectedValue == n.Trim
                         select n;
        }

        if (ddlColor.Text != "")
        {
          queryResults = from n in queryResults
                         where ddlColor.SelectedValue == n.Color
                         select n;
        }

        if (ddlTransmission.Text != "")
        {
          queryResults = from n in queryResults
                         where ddlTransmission.SelectedValue == n.Transmission
                         select n;
        }

        if (tbListPriceLow.Text != "" )
        {
          int low = 0;
          if(!int.TryParse(tbListPriceLow.Text, out low)){
            lblListPrice.ForeColor = System.Drawing.Color.Red;
            return;
          }

          queryResults = from n in queryResults
                         where low <= n.Price
                         select n;
        }

        if (tbListPriceHigh.Text != "")
        {
          int high = 0;
          if (!int.TryParse(tbListPriceHigh.Text, out high))
          {
            lblListPrice.ForeColor = System.Drawing.Color.Red;
            return;
          }

          queryResults = from n in queryResults
                         where high >= n.Price
                         select n;
        }

        var gridSource = from n in queryResults
                         select new
                         {
                           ID = n.Car_ID,
                           Model = n.Model,
                           Trim = n.Trim,
                           Color = n.Color,
                           Transmission = n.Transmission,
                           Location = n.Location,
                           Price = n.Price
                         };

        GridView1.DataSource = gridSource;
        Session["DataSource"] = queryResults;
        GridView1.DataBind();
      }

      protected void tbListPriceLow_TextChanged(object sender, EventArgs e)
      {

      }

      protected void tbListPrice0_TextChanged(object sender, EventArgs e)
      {

      }

      protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
      {
        decimal salesPrice;
        int carID = (int)GridView1.SelectedDataKey.Value;
        string previousPage = (string)Session["PreviousPage"];
        Session["Car_ID"] = carID;

        using (VWCTSDataContext db = new VWCTSDataContext())
        {
          salesPrice = (from n in db.Cars
                        where n.Car_ID == carID
                        select n.Price).Single();
        }

        Session["Sales_Price"] = salesPrice;

        if (previousPage != null)
          Response.Redirect(previousPage);
        else
          Response.Redirect("Process_Order.aspx");
      }

      protected void GridView1_PageIndexChanging(object sender, GridViewPageEventArgs e)
      {
        IQueryable<Car> source = (IQueryable<Car>)Session["DataSource"];
        var gridSource = from n in source
                         select new
                         {
                           ID = n.Car_ID,
                           Model = n.Model,
                           Trim = n.Trim,
                           Color = n.Color,
                           Transmission = n.Transmission,
                           Location = n.Location,
                           Price = n.Price
                         };

        GridView1.DataSource = gridSource;
        GridView1.PageIndex = e.NewPageIndex;
        GridView1.DataBind();
        
      }

      protected void GridView1_DataBound(object sender, EventArgs e)
      {
        if(GridView1.PageCount > 1)
          GridView1.BottomPagerRow.Visible = true;
      }

      protected void GridView1_Sorting(Object obj, GridViewSortEventArgs e)
      {
        tbCarID.Text = e.SortExpression.ToString() + " " + e.SortDirection.ToString()+ " | " + GridView1.SortDirection.ToString();
        IQueryable<Car> source = (IQueryable<Car>)Session["DataSource"];
        var gridSource = from n in source
                         select new
                         {
                           ID = n.Car_ID,
                           Model = n.Model,
                           Trim = n.Trim,
                           Color = n.Color,
                           Transmission = n.Transmission,
                           Location = n.Location,
                           Price = n.Price
                         };


        GridView1.DataSource = gridSource;
        e.SortDirection = e.SortDirection;
        e.SortExpression = e.SortExpression;
        GridView1.DataBind();
      }

      protected void GridView1_RowEditing(object sender, GridViewEditEventArgs e){
        int row = e.NewEditIndex;
        int carID = (int)GridView1.DataKeys[row].Value;
      }

      protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e){
        int row = e.RowIndex;
        int carID = (int)GridView1.DataKeys[row].Value;

        IQueryable<Car> dataSource = (IQueryable<Car>)Session["DataSource"];
        var source = from n in dataSource
                     where n.Car_ID != carID
                     select n;
        Session["DataSource"] = source;

        VWCTSDataContext db = new VWCTSDataContext();
        var options = from n in db.Car_Options
                      where n.Car_ID == carID
                      select n;

        foreach (var n in options)
        {
          db.Car_Options.DeleteOnSubmit(n);
        }

        Car deleteCar = (from n in db.Cars
                         where n.Car_ID == carID
                         select n).Single();

        db.Cars.DeleteOnSubmit(deleteCar);
        db.SubmitChanges();

        var gridSource = from n in source
                         select new
                         {
                           ID = n.Car_ID,
                           Model = n.Model,
                           Trim = n.Trim,
                           Color = n.Color,
                           Transmission = n.Transmission,
                           Location = n.Location,
                           Price = n.Price
                         };

        GridView1.DataSource = gridSource;
        GridView1.DataBind();
      }

      protected void GridView1_RowCommand(object sender, GridViewCommandEventArgs e){
        string command = e.CommandName;
        
        if (command == "ShowDetails")
        {
          int row = int.Parse((string)e.CommandArgument);
          int carID = (int)GridView1.DataKeys[row].Value;
          Session["Selected Car"] = carID;
          Response.Redirect("Car.aspx");
        }
      }
    }
}


