<?xml version="1.0" encoding="utf-8"?>
<Database Name="VWCTS" Class="VWCTSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MannyR\SQLEXPRESS;Initial Catalog=VWCTS;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="VWCTSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Trim" Member="Trims">
    <Type Name="Trim">
      <Column Name="Model" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trim" Member="Trim1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Customer_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Area_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Street_Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Zip_Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Transaction" Member="Transactions" ThisKey="Customer_ID" OtherKey="Customer_ID" Type="Transaction" />
      <Association Name="Customer_History" Member="Histories" ThisKey="Customer_ID" OtherKey="Customer_ID" Type="History" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Employee_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Area_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Street_Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Zip_Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Transaction" Member="Transactions" ThisKey="Employee_ID" OtherKey="Employee_ID" Type="Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.Optional_Packages" Member="Optional_Packages">
    <Type Name="Optional_Package">
      <Column Name="Package_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trim" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Option_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Optional_Package_Car_Option" Member="Car_Options" ThisKey="Package_ID" OtherKey="Package_ID" Type="Car_Option" />
    </Type>
  </Table>
  <Table Name="dbo.Photo" Member="Photos">
    <Type Name="Photo">
      <Column Name="Car_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Member="Photo1" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Car_Photo" Member="Car" ThisKey="Car_ID" OtherKey="Car_ID" Type="Car" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Transaction]" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customer_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Employee_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Car_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Down_Payment" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Amount_Financed" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Trade_Value" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Sales_Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Transaction" Member="Customer" ThisKey="Customer_ID" OtherKey="Customer_ID" Type="Customer" IsForeignKey="true" />
      <Association Name="Employee_Transaction" Member="Employee" ThisKey="Employee_ID" OtherKey="Employee_ID" Type="Employee" IsForeignKey="true" />
      <Association Name="Car_Transaction" Member="Car" ThisKey="Car_ID" OtherKey="Car_ID" Type="Car" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Car_Options" Member="Car_Options">
    <Type Name="Car_Option">
      <Column Name="Car_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Package_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Optional_Package_Car_Option" Member="Optional_Package" ThisKey="Package_ID" OtherKey="Package_ID" Type="Optional_Package" IsForeignKey="true" />
      <Association Name="Car_Car_Option" Member="Car" ThisKey="Car_ID" OtherKey="Car_ID" Type="Car" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car">
      <Column Name="Car_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VIN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trim" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Transmission" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Invoice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Miles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Car_Photo" Member="Photos" ThisKey="Car_ID" OtherKey="Car_ID" Type="Photo" />
      <Association Name="Car_Transaction" Member="Transactions" ThisKey="Car_ID" OtherKey="Car_ID" Type="Transaction" />
      <Association Name="Car_Car_Option" Member="Car_Options" ThisKey="Car_ID" OtherKey="Car_ID" Type="Car_Option" />
      <Association Name="Car_History" Member="Histories" ThisKey="Car_ID" OtherKey="Car_ID" Type="History" />
    </Type>
  </Table>
  <Table Name="dbo.History" Member="Histories">
    <Type Name="History">
      <Column Name="History_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customer_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Car_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Car_History" Member="Car" ThisKey="Car_ID" OtherKey="Car_ID" Type="Car" IsForeignKey="true" />
      <Association Name="Customer_History" Member="Customer" ThisKey="Customer_ID" OtherKey="Customer_ID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Update_Miles" Method="Update_Miles">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="m" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Update_Customer" Method="Update_Customer">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="First" Parameter="first" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Last" Parameter="last" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Area" Parameter="area" Type="System.Int32" DbType="Int" />
    <Parameter Name="Phone" Parameter="phone" Type="System.Int32" DbType="Int" />
    <Parameter Name="Street" Parameter="street" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Zip" Parameter="zip" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>